name: corbanmailloux
markdown: redcarpet
highlighter: pygments
encoding: UTF-8

url: http://shredify.me

# Owner/author information
owner:
  name:           Corban
  full-name:      Corban Mailloux
  # Gravatar Image (used in About Page)
  image:          http://s.gravatar.com/avatar/3993a2a8a38ac82b7f8ba71defb76031


# Limit what is hosted on the site.
exclude: ["runServer.bat", "CNAME", "Gemfile", "Gemfile.lock", "README.md"]


collections:
  celebs:
    output: true
    permalink: /:path/