name: corbanmailloux
markdown: redcarpet
highlighter: pygments
encoding: UTF-8

url: https://shredify.me

# Owner/author information
owner:
  name:           Corban
  full-name:      Corban Mailloux

# Limit what is hosted on the site.
exclude: ["runServer.bat", "CNAME", "README.md", ".gitignore", ".pleeeaserc"]

collections:
  celebs:
    output: true
    permalink: /:path/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "celebs"
    values:
      layout: "shred"
      audio: shred
